In [3]:
import numpy as np

from sklearn.preprocessing import MinMaxScaler

data = np.array([1, 3, 5, 6, 7, 8, 9, 10, 12, 18, 20,12])

scaler = MinMaxScaler(feature_range=(0,1))

data = scaler.fit_transform(data.reshape(-1,1))
data

array([[0.        ],
       [0.10526316],
       [0.21052632],
       [0.26315789],
       [0.31578947],
       [0.36842105],
       [0.42105263],
       [0.47368421],
       [0.57894737],
       [0.89473684],
       [1.        ],
       [0.57894737]])

# Many to one

In [6]:
X, Y = [], [] ## feature matrix

################## Prepare data for RNN ###########################

time_steps = 3

for i in range(len(data) - time_steps):

  X.append(data[i : i + time_steps]) # sequence window

  Y.append(data[i + time_steps]) # next value after the window

X = np.array(X) ## convert to array
Y = np.array(Y)
X = X.reshape(-1, time_steps, 1)
X

array([[[0.        ],
        [0.10526316],
        [0.21052632]],

       [[0.10526316],
        [0.21052632],
        [0.26315789]],

       [[0.21052632],
        [0.26315789],
        [0.31578947]],

       [[0.26315789],
        [0.31578947],
        [0.36842105]],

       [[0.31578947],
        [0.36842105],
        [0.42105263]],

       [[0.36842105],
        [0.42105263],
        [0.47368421]],

       [[0.42105263],
        [0.47368421],
        [0.57894737]],

       [[0.47368421],
        [0.57894737],
        [0.89473684]],

       [[0.57894737],
        [0.89473684],
        [1.        ]]])

In [8]:
from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import SimpleRNN, GRU, LSTM, Dense,Input

model = Sequential([

  Input(shape=(time_steps, 1)), ## input layer (time-step,features)

  SimpleRNN(10, activation = 'relu'), ## hidden state unit = 10

  Dense(1, activation = 'sigmoid') ## output layer = 1

])

model.compile(optimizer='adam', loss='mse')

model.fit(X, Y, epochs=50, verbose=1)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 0.0624
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0618
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0613
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0608
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0603
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0598
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0594
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0589
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0585
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0582
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0578
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0575
Epoch 13/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0571
Epoch 14/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0568
Epoch 15/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0565
Epoch 16/50
1/1 ━━━━━━━━━━━━━━━━━━━━

In [9]:
from sklearn.metrics import mean_squared_error

result = model.predict(X)

print(mean_squared_error(Y, result))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 477ms/step
0.05195733064347283


In [11]:
X

array([[[0.        ],
        [0.10526316],
        [0.21052632]],

       [[0.10526316],
        [0.21052632],
        [0.26315789]],

       [[0.21052632],
        [0.26315789],
        [0.31578947]],

       [[0.26315789],
        [0.31578947],
        [0.36842105]],

       [[0.31578947],
        [0.36842105],
        [0.42105263]],

       [[0.36842105],
        [0.42105263],
        [0.47368421]],

       [[0.42105263],
        [0.47368421],
        [0.57894737]],

       [[0.47368421],
        [0.57894737],
        [0.89473684]],

       [[0.57894737],
        [0.89473684],
        [1.        ]]])

In [13]:
Y

array([[0.26315789],
       [0.31578947],
       [0.36842105],
       [0.42105263],
       [0.47368421],
       [0.57894737],
       [0.89473684],
       [1.        ],
       [0.57894737]])

In [12]:
result

array([[0.5319419 ],
       [0.5364509 ],
       [0.5388576 ],
       [0.5424369 ],
       [0.5460118 ],
       [0.54958194],
       [0.5559081 ],
       [0.57339364],
       [0.5812699 ]], dtype=float32)

# Many to Many

In [14]:
X, Y = [], [] ## feature matrix

time_steps = 3
output_length = 2

################## Prepare data for RNN ###########################

for i in range(len(data) - time_steps - output_length + 1):
  X.append(data[i : i + time_steps])
  Y.append(data[i+ time_steps : i + time_steps +output_length])

X = np.array(X) ## convert to array
Y = np.array(Y)
X = X.reshape(-1, time_steps, 1) # (samples, time_steps, features)
Y= Y.reshape(-1, output_length,1) #(samples, output_length, features)

In [15]:
from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import SimpleRNN, GRU, LSTM, Dense,Input,RepeatVector

model = Sequential([

Input(shape=(time_steps, 1)), ## input layer (time-step, features)

LSTM(10, activation = 'relu'), ## Seq. Encoder

RepeatVector(output_length),

LSTM(10, activation = 'relu', return_sequences=True), ## Seq. Decoder

Dense(1, activation = 'sigmoid') ## output layer = 1

])

model.compile(optimizer='adam', loss='mse')

model.fit(X, Y, epochs = 50, verbose = 1)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - loss: 0.0623
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0622
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0621
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0620
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0619
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0618
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0617
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0616
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0615
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0614
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.0613
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0613
Epoch 13/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0612
Epoch 14/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0611
Epoch 15/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0610
Epoch 16/50
1/1 ━━━━━━━━━━━━━━━━━━━━